[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_url = "http://127.0.0.1:8545"
chain_id = 31337

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
